### ISSUE TITLE
New Account Bindings for go-ethereum

### ISSUE THREAD

**Issue by jarradh** [status-im/go-ethereum#11]
param to allow whisper injection

**Comment by dwhitena** [comment]
@jarradh so basically I need to add a binding for creating a new Geth account?  Does this include unlock as well?

**Comment by jarradh** [comment]
correct, unlock is seperate, lets discuss (ideally with @adrian-tiberius) because it involves;
1) checking if account can be unlocked with given password
2) signing transaction
in all other cases we kind of want the account to be locked (except for whisper)

**Comment by dwhitena** [comment]
@jarradh Ok.  Let's discuss with @adrian-tiberius.

**Comment by dwhitena** [comment]
In progress here: https://github.com/status-im/status-go/pull/1

**Comment by farazdagi** [comment]
outdated
