### ISSUE TITLE
Keep peers for supported subprotocol

### ISSUE THREAD

**Issue by jarradh** [status-im/go-ethereum#2]

**Comment by dwhitena** [comment]
Partially address here for `shh`, but we can generalize to a `subprotocols` flag that specifies whatever subset of protocols we are going to use.

**Comment by dwhitena** [comment]
LES addressed with https://github.com/status-im/go-ethereum/pull/6.  Also, this logic should work with swarm when if merged.  So I think this should be closed.  Yeah?

**Comment by jarradh** [comment]
actually, no. 

Each subprotocol is now supposed to manage it's own set of peers. we should make this happen

**Comment by dwhitena** [comment]
Ah, good distinction.  This will require changes to each respective protocol then?  Similar to what we discussed with LES?

**Comment by jarradh** [comment]
Yeah I think we should touch base with the guys on how to best implement that, i was thinking there would be if we can create a generic peer management mechanism that each protocol just 'uses' in place of the global one geth has atm, what do you think?

**Comment by dwhitena** [comment]
I think that would be ideal, but I would definitely want to get buy in from the people working on at least a couple of the protocols.  That way they can plan on that as well.  I would much rather have that than a bunch of redundant logic everywhere.
