### ISSUE TITLE
Disable `eth.accounts` method

### ISSUE THREAD

**Issue by rasom** [status-im/go-ethereum#25]
`eth.accounts` (`eth.getAccounts()`) method should not be accessible via RPC.

**Comment by jarradh** [comment]
well, it can be accessible, it just needs to return derivative child accounts from HD wallet

**Comment by rasom** [comment]
I thought we will have a separate method for this. But if so I will just close this issue and add more description here https://github.com/status-im/go-ethereum/issues/24 .

**Comment by jarradh** [comment]
if we need a seperate method for internal use it should be a binding

**Comment by jarradh** [comment]
json-rpc methods are assumed to be public for anyone to use

**Comment by rasom** [comment]
As i understand we need this method to be public, it was discussed in terms of `token` dapp.
