### ISSUE TITLE
Implement event logger

### ISSUE THREAD

**Issue by themue** [status-im/go-ethereum#47]
Implement `EventLogger` with following exported functions:

```
func NewEventLogger(o *ObserverChain, keyPrefix []byte) *EventLogger

func (e *EventLogger) AddEvent(key []byte, event interface{})

// NewChildLogger returns a new logger with the same observer chain and the new
// key prefix appended to the existing one.
func (e *EventLogger) NewChildLogger(keyPrefix []byte) *EventLogger
```

Process of adding one event is:

- get current unix nano time
- rlp encode event
- get trie from e.o
- add new entry in trie: `e.keyPrefix + key + BigEndian(time) -> eventRlp`
- unlock trie

**Comment by themue** [comment]
Assigned to Zoltán.

**Comment by b00ris** [comment]
Reopen the issue if needed.
