### ISSUE TITLE
Implement Ultra Light Client Mode

### ISSUE THREAD

**Issue by themue** [status-im/go-ethereum#48]
See https://gist.github.com/zsfelfoldi/7da2b802824569d2d159d5d06eeda14c

- [x] Adding the ultra light client option
- [x] Requesting signed headers
- [x] Implementing the trusted validation logic
- [x] Switching off header PoW validation
- [x] Modifying the server pool to always try to connect to them
- [ ] Option for trusted announce server

**Comment by b00ris** [comment]
Done
