### ISSUE TITLE
introduce whisperEnabled flag into geth accounts

### ISSUE THREAD

**Issue by jarradh** [status-im/go-ethereum#8]
on creation of account, have an argument that adds a whisperEnabled flag to the geth account and add it to the whisper keystore

on unlock of account, if has whisperEnabled flag, add it to the whisper keystore

**Comment by dwhitena** [comment]
Adding the data to the geth account is done here: https://github.com/status-im/go-ethereum/pull/7

Still need to add to the whisper keystore on unlock.

**Comment by dwhitena** [comment]
Done with https://github.com/status-im/go-ethereum/pull/7
