### ISSUE TITLE
Watch for shh messages with len(keys) > 0

### ISSUE THREAD

**Issue by dwhitena** [status-im/go-ethereum#9]
It seems like whisper can receive messages, but upon `shh.newIdentity()` or injection of an unlocked geth account, whisper stops listening.

-if the len(keys) == 0 them it tries to open the message withouth decryption

-if len(keys)> 0 like we have after newIndentity it tries to decrypt and probably fails

**Comment by dwhitena** [comment]
Note, this could either be an issue in the decryption or with the console as noted by @adrian-tiberius:

```
it might also not have anything to do with whisper and could be a console problem
because, like I said, it worked when we used it in status app
```

**Comment by dwhitena** [comment]
Ok, an update on this situation.  I have tracked down the bug to here: 

```
// open tries to decrypt a whisper envelope with all the configured identities,
// returning the decrypted message and the key used to achieve it. If not keys
// are configured, open will return the payload as if non encrypted.
func (self *Whisper) open(envelope *Envelope) *Message {
	// Short circuit if no identity is set, and assume clear-text
	if len(self.keys) == 0 {
		if message, err := envelope.Open(nil); err == nil {
			return message
		}
	}
	// Iterate over the keys and try to decrypt the message
	for _, key := range self.keys {
		message, err := envelope.Open(key)
		if err == nil {
			message.To = &key.PublicKey
			return message
		} else if err == ecies.ErrInvalidPublicKey {
			return message
		}
	}
	// Failed to decrypt, don't return anything
	return nil
}
```

In `whisper.go`.  When keys exist it is trying to decrypt all messages and failing.  It seems to continue looping, while generating decrytion errors.  I am trying to modify this to (i) successfully decrypt when decryption is needed (because not all whisper messages are encrypted), and (ii) identify the whisper identities as valid public keys.

**Comment by dwhitena** [comment]
Note also, if I disable the decryption here for the loop over keys, I can send/receive messages with new/injected identities.  It just has issues in the decryption.

**Comment by adrian-tiberius** [comment]
for receiving normal messages without explicit 'to' parameter, the error with decrypt should be ecies.ErrInvalidPublicKey. So when trying to decrypt with one of the keys it should go on the second if branch,

**Comment by dwhitena** [comment]
Thanks @adrian-tiberius.  Yeah, the logic makes sense but something is not responding as expected, because the original message is not returned.  I think it has to do with how the keys are stored and used with Open.  But looking into that now.

**Comment by dwhitena** [comment]
This is fixed for *unencrypted* messages (e.g., those withotu an explicit "to" field) in https://github.com/status-im/go-ethereum/pull/7/commits/e7203990549bccf4ecb72672251517745cc14af4.  Working on the encrypted side.  Basically the error handling was wrong.

```
> 
> 
> shh.newIdentity()
"0x044e54525927077d67428724e282b36e7c3a62a818ca5d2ad05d121826bb4c25245240c96fa7086303cc63a5f6b8936c512f9fb59321b1b0bc8de3a918dc4d6303"
> 
> 
> {opics": ["Hello"]}).watch(function(data){console.log("got a hello message");console.log(data);});
{
  callbacks: [function(data)],
  filterId: "0x0",
  getLogsCallbacks: [],
  implementation: {
    getLogs: function(),
    newFilter: function(),
    poll: function(),
    uninstallFilter: function()
  },
  options: {
    address: undefined,
    from: undefined,
    fromBlock: undefined,
    to: undefined,
    toBlock: undefined,
    topics: ["0x48656c6c6f"]
  },
  pollFilters: [],
  requestManager: {
    polls: {
      0x0: {
        data: {...},
        id: "0x0",
        callback: function(error, messages),
        uninstall: function()
      }
    },
    provider: {
      newAccount: function(),
      send: function(),
      sendAsync: function(),
      unlockAccount: function()
    },
    timeout: {},
    poll: function(),
    reset: function(keepIsSyncing),
    send: function(data),
    sendAsync: function(data, callback),
    sendBatch: function(data, callback),
    setProvider: function(p),
    startPolling: function(data, pollId, callback, uninstall),
    stopPolling: function(pollId)
  },
  formatter: function(post),
  get: function(callback),
  stopWatching: function(),
  watch: function(callback)
}
> 
> 
> 
> 
> got a hello message
```

**Comment by adrian-tiberius** [comment]
Not sure if we need to have multiple keys in whisper, or if I understand the code right, but from what I can see with this change, only the first key is tested and a message is returned if it fails.

**Comment by jarradh** [comment]
Whisper is supposed to handle multiple keys, DApps will be creating identities all over the place

**Comment by dwhitena** [comment]
Yes @adrian-tiberius.  It tries to decrypt for all keys.  Then for the ones that fail, tries to open without encryption.

**Comment by dwhitena** [comment]
Should work with multiple keys.  I will test that for sure though.

**Comment by dwhitena** [comment]
Should be fixed here: https://github.com/status-im/go-ethereum/pull/10

**Comment by jarradh** [comment]
@adrian-tiberius could you please verify this on your end?

**Comment by adrian-tiberius** [comment]
checked and it works.
